### PR TITLE
Automated testing via TravisCI

### PR DESCRIPTION
**Pull request by cbas**
- [x] ~~Mocha via Zuul and Saucelabs~~
- [x] ~~Tape via Smokestack~~
- [x] Mocha via Karma
- [x] Isparta with Browserify for Karma
- [x] Codecov uploads
- [x] Saucelabs from Travis
- [x] Local browser on Codeship

### CODE REVIEW

**Comment by cbas** [comment]
Refactored to use Stylus instead of PostCSS/CSSNext. To help with prefixing it loads the Stylus helper library `nib` in Zuul, Gulp, and Smokestack. Modified substack/insert-css#14 to support shadow dom injecting. No source maps yet.

I think at some point I'd like to get back into PostCSS/NextCSS because it seems more future-proof. Another alternative is to use `autoprefixer` with Stylus. (thanks @rstacruz)

**Comment by cbas** [comment]
Wow that wasn't supposed to pass.

**Comment by eddiemoore** [comment]
:+1: :ship: :shipit: :ship:

**Comment by cbas** [comment]
:heart: ty

**Pull request merged**
