### PR TITLE
checking coverage output

### PR DESCRIPTION
**Pull request by stevepeak**
Please do not merge, just checking out the coverage data. Thanks!

### CODE REVIEW

**Comment by cbas** [comment]
Running this locally:
https://gist.github.com/cbas/eb99a3045df80d5e9e0d
(Please forgive the Windows paths. Hope that doesn't make it worse.)

**Comment by cbas** [comment]
@eddiemoore Aside: Apparently the build fails because Travis can not connect to Sauce Labs when triggered by a PR from a fork. We should look into using [local PhantomJS for forked PR builds](http://stackoverflow.com/questions/22749762/how-to-tell-gruntfile-to-just-test-phantomjs-on-a-pull-request).

@stevepeak Thanks very much for your personal attention. Really appreciate any help to get our code coverage results working even better.

**Comment by stevepeak** [comment]
@cbas thanks for sharing this with me. I'm working on this now. Do you have the commit this report is in reference to so I can verify some information.

Thanks!

**Comment by stevepeak** [comment]
> source from app/components/mig/me/me.js

```js
/*global HTMLElement */
import insertCss from 'insert-css'
import Beachball from 'migme-beachball/src'
import MigButton from '../button'
import MigPanel from '../panel'
import css from './me.styl'
import html from './me.jade'

class Me extends HTMLElement {
  createdCallback () {
    this.beachball = new Beachball()

    let root = this.createShadowRoot()
```

```
BRDA:8,1,0,1
BRDA:8,1,1,1
BRDA:8,2,0,1
BRDA:8,2,1,0
BRDA:8,3,0,1
BRDA:8,3,1,0
BRDA:8,4,0,0
BRDA:8,4,1,1
BRDA:10,5,0,0
BRDA:10,5,1,6
BRDA:10,6,0,6
BRDA:10,6,1,6
BRDA:12,7,0,0
BRDA:12,7,1,0
```
> above from https://gist.github.com/cbas/eb99a3045df80d5e9e0d#file-info-lcov-L108-L115

```
Branch coverage information is stored which one line per branch:
         BRDA:<line number>,<block number>,<branch number>,<taken>
```
> above from http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

Therefore line `8` and `12` have coverage data which is expressed properly on Codecov [here](https://codecov.io/github/migme/surfboard/app/components/mig/me/me.js?ref=master#l-8) but does not line up on the code....

Are you using EC6? I've heard so people have issues on coverage, but I need to dig up threads to reference to. Perhaps you can help me figure this out...

**Comment by cbas** [comment]
@stevepeak This log came from running against master. That's d3bf8fa55271c11876b7a005b32228ffa13f5d5a as of last night.

The tests and app are written in ES6, yes. They get transpiled using Browserify with Babelify and [karma-source-map-support](https://www.npmjs.com/package/karma-source-map-support) to be able to debug with source maps in the browser. The coverage comes from Istanbul, with Isparta as instrumenter. There is a broken link somewhere in the source map chain, I think.

:sweat_smile:

**Comment by cbas** [comment]
@stevepeak This log came from running against master. That's d3bf8fa55271c11876b7a005b32228ffa13f5d5a as of last night.

The tests and app are written in ES6, yes. They get transpiled using Browserify with Babelify and [karma-source-map-support](https://www.npmjs.com/package/karma-source-map-support) to be able to debug with source maps in the browser. The coverage comes from Istanbul, with Isparta as instrumenter. There is a broken link somewhere in the source map chain, I think.

:sweat_smile:

**Comment by cbas** [comment]
FYI I've also had issues running karma with code coverage and source maps simultaneously. I suspect Istanbul is at fault since it has no support for source maps yet ([WIP branch](https://github.com/gotwarlost/istanbul/compare/source-map)).

**Comment by stevepeak** [comment]
@eddiemoore or @cbas can we schedule a time to chat on Skype to try to fix this issue. I need to learn more about whats going on with ES6's issues. Thanks

**Comment by cbas** [comment]
Sure -- we'll hang out in https://gitter.im/codecov/support

**Pull request closed without merging**
